name       : unicode-character-database
version    : 9.0.0
release    : 2
source     :
    - http://www.unicode.org/Public/zipped/9.0.0/UCD.zip : df9e028425816fd5117eaea7173704056f88f7cd030681e457c6f3827f9390ec
    - http://www.unicode.org/Public/zipped/9.0.0/Unihan.zip : 6afdd48fb3c5d79a527ed27ce2582b2f684c09e16f5d0837fe7e5b0204f46362
license    : MIT
component  : programming
summary    : The Unicode Character Database (UCD) consists of a number of data files listing Unicode character properties and related data.
description: |
    The Unicode Character Database (UCD) consists of a number of data files listing Unicode character properties and related data.
builddeps  :
    - unzip
setup      : |
    unzip $sources/Unihan.zip
install    : |
    install -dm00644 $installdir/usr/share/unicode-character-database/
    cp -R * $installdir/usr/share/unicode-character-database/
    cp $sources/*.zip $installdir/usr/share/unicode-character-database/
