name       : unicode-character-database
version    : 10.0.0
release    : 4
source     :
    - http://www.unicode.org/Public/zipped/10.0.0/UCD.zip : cb26d649f8bac8b12f69e2fbcd77d1759ecdcd7c8e8f1c4385a9c5a36cf14891
    - http://www.unicode.org/Public/zipped/10.0.0/Unihan.zip : 01232063a8529636cf155ba7a1dbad329cb2e63acde83a3d607b5eafa8f933a5
license    : MIT
component  : programming
summary    : The Unicode Character Database (UCD)
description: |
    The Unicode Character Database (UCD) consists of a number of data files listing Unicode character properties and related data.
builddeps  :
    - unzip
setup      : |
    unzip $sources/Unihan.zip
install    : |
    install -dm00644 $installdir/usr/share/unicode-character-database/
    install -dm00644 $installdir/usr/share/unicode/
    cp -R * $installdir/usr/share/unicode-character-database/
    cp $sources/*.zip $installdir/usr/share/unicode-character-database/
    ln -s /usr/share/unicode-character-database $installdir/usr/share/unicode/ucd
